### PR TITLE
Update

### PR DESCRIPTION
**Pull request by joamatab**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
see above - once that is fixed I will merge.

**Comment by joamatab** [comment]
perfect! i removed them, and we can add them later if needed

thank you @beckermr !

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by joamatab** [comment]
Awesome! 

What's the process to automatically update phidl to the latest version?
https://anaconda.org/conda-forge/phidl

**Comment by beckermr** [comment]
close or merge the four open PRs and the bot will issue more.

**Comment by joamatab** [comment]
Awesome! I just closed them

thank you Matthew!

**Comment by wshanks** [comment]
1.6.1 was added in this PR. You just need to wait a few hours for it to get populated in the CDN.

I think it would be worth adding the maintainer of the upstream project based on this comment: https://github.com/amccaugh/phidl/issues/148#issuecomment-1153323486

**Comment by joamatab** [comment]
Any ideas how long does the updating take place?

are there any ways to trigger a package update from phidl?

**Comment by wshanks** [comment]
It usually only takes a few hours, so 1.6.1 should be available now but I don't see it. There are a couple steps (finding updated packages, building new packages, uploading built packages, wait for CDN to populate) that can take 30-60 minutes to run which is why I say a few hours. We would need to look through the logs of the automated steps to see if we could find where phidl is now. I haven't looked in a while, so I don't remember exactly where to look. I think part of it is https://github.com/regro/autotick-bot/actions?query=is%3Ain_progress++.

The bot should detect new PyPI releases and open PR's here automatically that you can merge, so triggering an update should not be too necessary. An automation could be set up to create the PR here from phidl's repo if you didn't want to wait the ~1 hour for the bot to notice the new PyPI release.

**Comment by joamatab** [comment]
Hi @beckermr

How can we check the status of the conda update for phidl?

**Comment by wshanks** [comment]
It seems like the build CI did not run because of some fluke. chrisburr pushed an extra commit to retrigger the CI and it ran this time. It should be accessible with `conda` soon.

**Pull request merged**
